/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import AntColony.Ant;
import EDD.*;
import Grafo.*;
import static GUI.Menu.grafo;
import Grafo.DrawGraf;

/**
 *
 * @author santi
 */
public class Inicio extends javax.swing.JFrame {
    

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cancelar = new javax.swing.JButton();
        InputNumAnt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        InputNumCiclos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InputVisibilidadCiudad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InputFeromona = new javax.swing.JTextField();
        InputValorEvaporacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        iniciar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        InputCiudadInicial = new javax.swing.JTextField();
        InputCiudadFinal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 90, -1));

        InputNumAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNumAntActionPerformed(evt);
            }
        });
        jPanel1.add(InputNumAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 130, -1));

        jLabel1.setText("Numero de Hormigas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        InputNumCiclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNumCiclosActionPerformed(evt);
            }
        });
        jPanel1.add(InputNumCiclos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 130, -1));

        jLabel2.setText("Numero de Ciclos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        InputVisibilidadCiudad.setText("2");
        InputVisibilidadCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputVisibilidadCiudadActionPerformed(evt);
            }
        });
        jPanel1.add(InputVisibilidadCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 130, -1));

        jLabel3.setText(" Importancia de feromona (α)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 180, -1));

        jLabel4.setText("Visibilidad de Ciudad (β)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 160, -1));

        InputFeromona.setText("1");
        InputFeromona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFeromonaActionPerformed(evt);
            }
        });
        jPanel1.add(InputFeromona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, -1));

        InputValorEvaporacion.setText("0.5");
        InputValorEvaporacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputValorEvaporacionActionPerformed(evt);
            }
        });
        jPanel1.add(InputValorEvaporacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, -1));

        jLabel5.setText("Valor de Evaporacion (ρ)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Recorrido de Hormiga");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 160, -1));

        iniciar.setText("Iniciar Simulacion");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        jPanel1.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 150, -1));

        jLabel7.setText("Ciudad Inicial");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        InputCiudadInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCiudadInicialActionPerformed(evt);
            }
        });
        jPanel1.add(InputCiudadInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, -1));

        InputCiudadFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCiudadFinalActionPerformed(evt);
            }
        });
        jPanel1.add(InputCiudadFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 130, -1));

        jLabel8.setText("Ciudad Final");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputNumAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNumAntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNumAntActionPerformed

    private void InputNumCiclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNumCiclosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNumCiclosActionPerformed

    private void InputVisibilidadCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputVisibilidadCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputVisibilidadCiudadActionPerformed

    private void InputFeromonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFeromonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFeromonaActionPerformed

    private void InputValorEvaporacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputValorEvaporacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputValorEvaporacionActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        int numCiclo = Integer. parseInt(InputNumCiclos.getText());
        int numAnt = Integer. parseInt(InputNumAnt.getText());
        
        double alpha = Double.parseDouble(InputFeromona.getText());
        double beta = Double.parseDouble(InputVisibilidadCiudad.getText());
        double rho = Double.parseDouble(InputValorEvaporacion.getText());
        
        String CiudadInicialStr = InputCiudadInicial.getText();
        String CiudadFinalStr = InputCiudadFinal.getText();
        
        Nodo CiudadInicial = grafo.getVertices().buscar(CiudadInicialStr);
        Nodo CiudadFinal = grafo.getVertices().buscar(CiudadFinalStr);
        
        
        
        for (int i = 0; i < numCiclo; i++) {
            for (int j = 0; j < numAnt; j++) {
                Ant ant = new Ant();
                ant.setCiudadActual(CiudadInicial);
                ant.recorridoAnt(alpha,beta,CiudadFinal);
                
            }
            
        }
        
        
        DrawGraf ant = new DrawGraf();
        ant.draw(grafo.getVertices());
    }//GEN-LAST:event_iniciarActionPerformed

    private void InputCiudadInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCiudadInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCiudadInicialActionPerformed

    private void InputCiudadFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCiudadFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCiudadFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField InputCiudadFinal;
    private javax.swing.JTextField InputCiudadInicial;
    private javax.swing.JTextField InputFeromona;
    private javax.swing.JTextField InputNumAnt;
    private javax.swing.JTextField InputNumCiclos;
    private javax.swing.JTextField InputValorEvaporacion;
    private javax.swing.JTextField InputVisibilidadCiudad;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
