/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.File;
import javax.swing.JFileChooser;
import Grafo.*;
import Grafo.DrawGraf;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author santi
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    static public GrafManager grafo = new GrafManager();
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Save = new javax.swing.JButton();
        AddVertex = new javax.swing.JButton();
        DeleteVertex = new javax.swing.JButton();
        Start = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        Upload = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShowFile = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Save.setText("Guardar Archivo");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel2.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, -1));

        AddVertex.setText("Agregar Ciudad");
        AddVertex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVertexActionPerformed(evt);
            }
        });
        jPanel2.add(AddVertex, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, -1));

        DeleteVertex.setText("Eliminar Ciudad");
        DeleteVertex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteVertexActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteVertex, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, -1));

        Start.setText("Iniciar");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        jPanel2.add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Title.setText("Ant Colony");
        jPanel2.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        Upload.setText("Subir Archivo");
        Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadActionPerformed(evt);
            }
        });
        jPanel2.add(Upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 150, -1));

        ShowFile.setColumns(20);
        ShowFile.setRows(5);
        jScrollPane1.setViewportView(ShowFile);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 140, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        if (grafo.getSubido()) {
            Inicio inicio = new Inicio();
            inicio.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Debe importar un archivo.");
        }
        
        
    }//GEN-LAST:event_StartActionPerformed

    private void DeleteVertexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteVertexActionPerformed
        if (grafo.getSubido()) {
            EliminarCiudad ciudad = new EliminarCiudad();
            ciudad.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Debe importar un archivo.");
        }
        

    }//GEN-LAST:event_DeleteVertexActionPerformed

    private void AddVertexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVertexActionPerformed
        if (grafo.getSubido()) {
            InsertarCiudad ciudad = new InsertarCiudad();
            ciudad.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Debe importar un archivo.");
        }
        
    }//GEN-LAST:event_AddVertexActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        grafo.write_txt();
    }//GEN-LAST:event_SaveActionPerformed

    private void UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadActionPerformed
        //Crea objeto FileChooser
        JFileChooser file=new JFileChooser();
        //Crea filtro para solo archivos txt
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT","txt");
        //pasa el filtro al filechooser
        file.setFileFilter(filtro);
        //muestra el filechooser
        file.showSaveDialog(this);
        //guarda el filechooser
        File guarda =file.getSelectedFile();
        try{
            String fileName = guarda.getName().toUpperCase();
            if (fileName.endsWith(".TXT") ) {
                VertexLista v1=grafo.read_text(guarda);
                grafo.setVertices(v1);
                JOptionPane.showMessageDialog(null, "El archivo se ha cargado de forma exitosa");
                this.ShowFile.setText(grafo.imprimir());

                //grafo.imprimir();

            }else{
                JOptionPane.showMessageDialog(null, "Ha introducido un tipo de archivo no valido");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"No ha introducido un archivo");
        }

    }//GEN-LAST:event_UploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddVertex;
    private javax.swing.JButton DeleteVertex;
    private javax.swing.JButton Save;
    protected static javax.swing.JTextArea ShowFile;
    private javax.swing.JButton Start;
    private javax.swing.JLabel Title;
    private javax.swing.JButton Upload;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
